name: Atualizar Dashboard Imoveis

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias vitais (QuintoAndar + VivaReal)
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas selenium webdriver-manager beautifulsoup4

      - name: Rodar o Super Robo
        run: python main.py

      - name: Guardar os novos dados
        run: |
          git config --global user.name "Robo Imobiliario"
          git config --global user.email "robo@exemplo.com"
          git add -A
          git commit -m "Atualizacao: QuintoAndar e VivaReal" || echo "Nenhuma mudanca detetada"
          git push
